[API]
# Change the baseUrl to point to the backend API server.
baseUrl = http://localhost:3000

[CONNECTION]
;STRING=Provider=SQLNCLI11;Persist Security Info=True;Initial Catalog=MYPAY_KIN;Data Source=DIN-STT
STRING=Provider=SQLNCLI11;Persist Security Info=True;Initial Catalog=MYPAY_JSM;Data Source=v1soho.com,1500

